<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class IncidentSeeder extends Seeder
{
    public function run(): void
    {
        DB::table('incidents')->insert([
            [
                'title' => 'Primary Database Connection Failure',
                'description' => 'Database server unreachable from application.',
                'severity' => 'CRITICAL',
                'status' => 'OPEN',
                'category_id' => 5,
                'assigned_to' => 2,
                'reported_by' => 1,
                'incident_date' => now(),
                'resolved_at' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'API Response Delay',
                'description' => 'Slow response detected on production API.',
                'severity' => 'HIGH',
                'status' => 'IN_PROGRESS',
                'category_id' => 3,
                'assigned_to' => 3,
                'reported_by' => 1,
                'incident_date' => now()->subHours(3),
                'resolved_at' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Network Packet Loss',
                'description' => 'Packet loss detected in internal network.',
                'severity' => 'MEDIUM',
                'status' => 'OPEN',
                'category_id' => 1,
                'assigned_to' => 2,
                'reported_by' => 1,
                'incident_date' => now()->subHours(5),
                'resolved_at' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Unauthorized Login Attempt',
                'description' => 'Multiple failed login attempts detected from suspicious IP addresses.',
                'severity' => 'HIGH',
                'status' => 'RESOLVED',
                'category_id' => 4,
                'assigned_to' => 3,
                'reported_by' => 1,
                'incident_date' => now()->subDay(),
                'resolved_at' => now(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Server CPU Spike',
                'description' => 'CPU usage exceeded 95% threshold for more than 10 minutes.',
                'severity' => 'LOW',
                'status' => 'CLOSED',
                'category_id' => 2,
                'assigned_to' => 2,
                'reported_by' => 1,
                'incident_date' => now()->subDays(2),
                'resolved_at' => now()->subDay(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'SSL Certificate Expiry Warning',
                'description' => 'SSL certificate for api.internal expires in 7 days. Renewal required immediately.',
                'severity' => 'HIGH',
                'status' => 'IN_PROGRESS',
                'category_id' => 4,
                'assigned_to' => 3,
                'reported_by' => 2,
                'incident_date' => now()->subHours(6),
                'resolved_at' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Disk Storage Capacity Warning',
                'description' => 'Production server disk usage at 92%. Log rotation and cleanup required.',
                'severity' => 'MEDIUM',
                'status' => 'OPEN',
                'category_id' => 2,
                'assigned_to' => 2,
                'reported_by' => 1,
                'incident_date' => now()->subHours(8),
                'resolved_at' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Memory Leak in Worker Process',
                'description' => 'Queue worker process memory usage growing unbounded. Restarted as temporary fix.',
                'severity' => 'HIGH',
                'status' => 'IN_PROGRESS',
                'category_id' => 3,
                'assigned_to' => 3,
                'reported_by' => 2,
                'incident_date' => now()->subHours(12),
                'resolved_at' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Email Delivery Failure',
                'description' => 'Transactional emails not delivered to users. SMTP relay returning 550 errors.',
                'severity' => 'HIGH',
                'status' => 'RESOLVED',
                'category_id' => 5,
                'assigned_to' => 2,
                'reported_by' => 1,
                'incident_date' => now()->subDays(1)->subHours(4),
                'resolved_at' => now()->subHours(10),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Backup Job Failure',
                'description' => 'Scheduled nightly database backup did not complete. Last successful backup 48 hours ago.',
                'severity' => 'CRITICAL',
                'status' => 'OPEN',
                'category_id' => 5,
                'assigned_to' => 2,
                'reported_by' => 1,
                'incident_date' => now()->subHours(14),
                'resolved_at' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Third-Party Payment Gateway Timeout',
                'description' => 'Payment processing requests timing out. Affecting checkout flow for all users.',
                'severity' => 'CRITICAL',
                'status' => 'RESOLVED',
                'category_id' => 3,
                'assigned_to' => 3,
                'reported_by' => 1,
                'incident_date' => now()->subDays(2)->subHours(2),
                'resolved_at' => now()->subDays(2),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Firewall Rule Misconfiguration',
                'description' => 'Incorrect firewall rule deployed blocking internal service communication.',
                'severity' => 'HIGH',
                'status' => 'CLOSED',
                'category_id' => 1,
                'assigned_to' => 2,
                'reported_by' => 3,
                'incident_date' => now()->subDays(3),
                'resolved_at' => now()->subDays(3)->addHours(2),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Application Deploy Rollback',
                'description' => 'v2.4.1 deployment caused 500 errors on checkout. Rolled back to v2.4.0.',
                'severity' => 'HIGH',
                'status' => 'CLOSED',
                'category_id' => 3,
                'assigned_to' => 3,
                'reported_by' => 2,
                'incident_date' => now()->subDays(3)->subHours(6),
                'resolved_at' => now()->subDays(3)->subHours(4),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'CDN Cache Poisoning Detected',
                'description' => 'Stale and incorrect responses served to users via CDN edge nodes.',
                'severity' => 'MEDIUM',
                'status' => 'RESOLVED',
                'category_id' => 4,
                'assigned_to' => 3,
                'reported_by' => 1,
                'incident_date' => now()->subDays(4),
                'resolved_at' => now()->subDays(4)->addHours(3),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Load Balancer Health Check Failure',
                'description' => 'Two of four app server nodes removed from rotation by load balancer health checks.',
                'severity' => 'CRITICAL',
                'status' => 'RESOLVED',
                'category_id' => 1,
                'assigned_to' => 2,
                'reported_by' => 1,
                'incident_date' => now()->subDays(4)->subHours(8),
                'resolved_at' => now()->subDays(4)->subHours(6),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Scheduled Maintenance Window Overrun',
                'description' => 'Database migration during maintenance window took 3x longer than estimated, causing extended downtime.',
                'severity' => 'MEDIUM',
                'status' => 'CLOSED',
                'category_id' => 5,
                'assigned_to' => 2,
                'reported_by' => 3,
                'incident_date' => now()->subDays(5),
                'resolved_at' => now()->subDays(5)->addHours(4),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'API Rate Limit Breach',
                'description' => 'A single client exceeded API rate limits causing degraded service for other tenants.',
                'severity' => 'LOW',
                'status' => 'CLOSED',
                'category_id' => 3,
                'assigned_to' => 3,
                'reported_by' => 1,
                'incident_date' => now()->subDays(6),
                'resolved_at' => now()->subDays(6)->addHour(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'DNS Resolution Failure',
                'description' => 'Internal DNS resolver returning NXDOMAIN for several microservice hostnames.',
                'severity' => 'HIGH',
                'status' => 'CLOSED',
                'category_id' => 1,
                'assigned_to' => 2,
                'reported_by' => 2,
                'incident_date' => now()->subDays(7),
                'resolved_at' => now()->subDays(7)->addHours(2),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Brute Force Attack on Admin Panel',
                'description' => 'Over 10,000 login attempts against /admin in a 1-hour window from rotating IPs.',
                'severity' => 'CRITICAL',
                'status' => 'RESOLVED',
                'category_id' => 4,
                'assigned_to' => 3,
                'reported_by' => 1,
                'incident_date' => now()->subDays(8),
                'resolved_at' => now()->subDays(8)->addHours(1),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Log Aggregation Service Down',
                'description' => 'Centralized log aggregation pipeline stopped ingesting. Logs accumulating on app servers.',
                'severity' => 'MEDIUM',
                'status' => 'CLOSED',
                'category_id' => 2,
                'assigned_to' => 2,
                'reported_by' => 3,
                'incident_date' => now()->subDays(9),
                'resolved_at' => now()->subDays(9)->addHours(3),
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}
